### ISSUE TITLE
fresh build of example does not work

### ISSUE THREAD

**Issue by kumavis** [joshmarinacci/voxeljs-next#43]
```
npm install
npm start
```

`localhost:8080`
```
ecsy.module.js:1437 Uncaught Error: createType expect type definition to implements the following functions: create, reset, clear
    at createType (ecsy.module.js:1437:1)
    at defineClonableType (index.js:25:20)
    at ./node_modules/ecsy-three/src/types/index.js (index.js:40:8)
    at __webpack_require__ (bootstrap:79:1)
    at ./node_modules/ecsy-three/src/index.js (index.js:1:1)
    at __webpack_require__ (bootstrap:79:1)
    at ./src/ecsy/input.js (input.js:1:1)
    at __webpack_require__ (bootstrap:79:1)
    at ./src/ecsy/mouse.js (mouse.js:1:1)
    at __webpack_require__ (bootstrap:79:1)
createType @ ecsy.module.js:1437
defineClonableType @ index.js:25
./node_modules/ecsy-three/src/types/index.js @ index.js:40
__webpack_require__ @ bootstrap:79
./node_modules/ecsy-three/src/index.js @ index.js:1
__webpack_require__ @ bootstrap:79
./src/ecsy/input.js @ input.js:1
__webpack_require__ @ bootstrap:79
./src/ecsy/mouse.js @ mouse.js:1
__webpack_require__ @ bootstrap:79
./src/ecsy/index.js @ index.js:1
__webpack_require__ @ bootstrap:79
./src/index.js @ index.js:1
__webpack_require__ @ bootstrap:79
(anonymous) @ bootstrap:152
__webpack_require__ @ bootstrap:79
checkDeferredModules @ bootstrap:45
(anonymous) @ bootstrap:152
(anonymous) @ bootstrap:152
ecsy.module.js:1437 Uncaught Error: createType expect type definition to implements the following functions: create, reset, clear
    at createType (ecsy.module.js:1437:1)
    at defineClonableType (index.js:25:20)
    at ./node_modules/ecsy-three/src/types/index.js (index.js:40:8)
    at __webpack_require__ (bootstrap:79:1)
    at ./node_modules/ecsy-three/src/index.js (index.js:1:1)
    at __webpack_require__ (bootstrap:79:1)
    at ./examples/src/index.js (index.js:1:1)
    at __webpack_require__ (bootstrap:79:1)
    at 1 (app.js:940:18)
    at __webpack_require__ (bootstrap:79:1)
```

**Comment by kumavis** [comment]
also generates a large diff in `example/package-lock.json`
